name: Test OS

on:
  push:
    branches: [matlab]

jobs:

  test:

    name: MATLAB ${{ matrix.matlab }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        matlab: [R2021b, R2022a, R2022b, R2023a, R2023b, R2024a, latest]

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB with optimization toolbox and parallel computing toolbox
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.matlab }}
          cache: true
          products: Optimization_Toolbox Parallel_Computing_Toolbox

      - name: Run tests
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
            test

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: out_${{ matrix.os }}_${{ matrix.matlab }}
          path: ./output